### ISSUE TITLE
Footer's download link leads to 404

### ISSUE THREAD

**Issue by brianzelip** [estrattonbailey/svbstrate#2]
Check the [download](https://github.com/estrattonbailey/svbstrate/blob/master/svbstrate_v0.5.1_complete.zip?raw=true) link in the footer at http://svbstrate.io/ !

**Comment by estrattonbailey** [comment]
Hey @brianzelip! Thanks for the heads up. That site and the files in this repo are in a dire state, sorry to say. I hope to have time in the next few weeks to give the whole project an overhaul. I've come along way with my development skills since I last updated svbstrate (switched from design to dev full time in Janurary). Check back soon!
